### ISSUE TITLE
es2015 preset error with this component

### ISSUE THREAD

**Issue by rgoldiez** [wkh237/react-native-animate-number#1]
First of all......... thank you thank you for creating this component!  I just grabbed it and I'm trying to just import it per the instructions in the `README.md` and I'm running into the following error.  I'm on RN 0.25.1 if that matters.

![image](https://cloud.githubusercontent.com/assets/10797610/15450265/d9f191fe-1f65-11e6-90e8-1713e387c5e9.png)

**Comment by rgoldiez** [comment]
If it's helpful at all.... I copied the index.js from this component into my own file, included that and it works perfectly.

**Comment by wkh237** [comment]
@rgoldiez , thanks for you're information !
I think it's because I misplaced the `.babelrc`, I'll fix the problem and publish a new version to npm.

**Comment by rgoldiez** [comment]
Awesome.  This is great work you've done!  Thanks for the contribution.
